### ISSUE TITLE
Incorrect analogRead() measurements

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/MicroMod_Artemis_Processor#4]
Howdy,

There currently appears to be an issue with obtaining correct analogRead() measurements with the Artemis Processor.

Plugging into the MicroMod Data Logging Carrier Board and running the Artemis example: `Example4_analogRead` reveals that when tied to GND, the analog measurement is correct (0). However, when 3.3 V is applied, the analog reading maxes out at ~15890/16384.

```
10:23:12.517 -> SparkFun Arduino Apollo3 Analog Read example
10:23:12.517 -> A0: 0	VCC/3: 8799 VCC: 3.22V	internalTemp: 26.85	vss: 0
10:23:12.620 -> A0: 0	VCC/3: 8799 VCC: 3.22V	internalTemp: 27.18	vss: 0
10:23:12.726 -> A0: 0	VCC/3: 8801 VCC: 3.22V	internalTemp: 27.54	vss: 0
10:23:12.799 -> A0: 0	VCC/3: 8806 VCC: 3.22V	internalTemp: 27.54	vss: 0
10:23:12.908 -> A0: 0	VCC/3: 8801 VCC: 3.22V	internalTemp: 27.32	vss: 0
10:23:13.010 -> A0: 0	VCC/3: 8801 VCC: 3.22V	internalTemp: 27.10	vss: 0
10:23:13.110 -> A0: 0	VCC/3: 8802 VCC: 3.22V	internalTemp: 27.21	vss: 0
10:23:13.213 -> A0: 0	VCC/3: 8801 VCC: 3.22V	internalTemp: 26.59	vss: 0
10:23:13.316 -> A0: 0	VCC/3: 8805 VCC: 3.22V	internalTemp: 27.10	vss: 0
10:23:13.417 -> A0: 0	VCC/3: 8803 VCC: 3.22V	internalTemp: 26.81	vss: 0
10:23:13.520 -> A0: 0	VCC/3: 8805 VCC: 3.22V	internalTemp: 27.21	vss: 0
10:23:13.626 -> A0: 0	VCC/3: 8801 VCC: 3.22V	internalTemp: 27.14	vss: 0
...
10:23:19.105 -> A0: 15889	VCC/3: 8808 VCC: 3.23V	internalTemp: 26.66	vss: 0
10:23:19.208 -> A0: 15882	VCC/3: 8801 VCC: 3.22V	internalTemp: 26.88	vss: 0
10:23:19.311 -> A0: 15891	VCC/3: 8799 VCC: 3.22V	internalTemp: 26.26	vss: 0
10:23:19.417 -> A0: 15890	VCC/3: 8808 VCC: 3.23V	internalTemp: 27.32	vss: 0
10:23:19.524 -> A0: 15894	VCC/3: 8808 VCC: 3.23V	internalTemp: 26.77	vss: 0
10:23:19.627 -> A0: 15890	VCC/3: 8800 VCC: 3.22V	internalTemp: 27.07	vss: 0
10:23:19.702 -> A0: 15882	VCC/3: 8801 VCC: 3.22V	internalTemp: 27.29	vss: 0
10:23:19.803 -> A0: 15885	VCC/3: 8806 VCC: 3.22V	internalTemp: 26.77	vss: 0
10:23:19.909 -> A0: 15880	VCC/3: 8802 VCC: 3.22V	internalTemp: 27.36	vss: 0
10:23:20.013 -> A0: 15883	VCC/3: 8799 VCC: 3.22V	internalTemp: 27.36	vss: 0
10:23:20.117 -> A0: 15885	VCC/3: 8802 VCC: 3.22V	internalTemp: 26.85	vss: 0
10:23:20.224 -> A0: 15892	VCC/3: 8802 VCC: 3.22V	internalTemp: 27.03	vss: 0
10:23:20.329 -> A0: 15878	VCC/3: 8802 VCC: 3.22V	internalTemp: 27.14	vss: 0
```

Similarly, when running the `ADC.ino` example included in the Artemis Processor repo, applying 3.3 V to both A0 and A1 reveals incorrect voltage measurements.

```
10:28:59.335 -> A0 voltage: 3.197	A1 voltage: 3.211	battvin: 6188	Batt voltage: 1.246
10:28:59.369 -> A0 voltage: 3.197	A1 voltage: 3.209	battvin: 6195	Batt voltage: 1.248
10:28:59.438 -> A0 voltage: 3.199	A1 voltage: 3.205	battvin: 6191	Batt voltage: 1.247
10:28:59.471 -> A0 voltage: 3.199	A1 voltage: 3.205	battvin: 6189	Batt voltage: 1.247
10:28:59.538 -> A0 voltage: 3.198	A1 voltage: 3.210	battvin: 6188	Batt voltage: 1.246
10:28:59.574 -> A0 voltage: 3.200	A1 voltage: 3.207	battvin: 6186	Batt voltage: 1.246
10:28:59.642 -> A0 voltage: 3.199	A1 voltage: 3.211	battvin: 6198	Batt voltage: 1.248
10:28:59.711 -> A0 voltage: 3.199	A1 voltage: 3.210	battvin: 6191	Batt voltage: 1.247
10:28:59.746 -> A0 voltage: 3.199	A1 voltage: 3.206	battvin: 6198	Batt voltage: 1.248
10:28:59.781 -> A0 voltage: 3.199	A1 voltage: 3.207	battvin: 6184	Batt voltage: 1.246
10:28:59.852 -> A0 voltage: 3.199	A1 voltage: 3.206	battvin: 6191	Batt voltage: 1.247
10:28:59.885 -> A0 voltage: 3.198	A1 voltage: 3.210	battvin: 6183	Batt voltage: 1.245
10:28:59.952 -> A0 voltage: 3.198	A1 voltage: 3.205	battvin: 6184	Batt voltage: 1.246
10:28:59.987 -> A0 voltage: 3.199	A1 voltage: 3.206	battvin: 6197	Batt voltage: 1.248
```

I suspect this issue is linked to the incorrect battery measurements in #3 and ultimately connected to the resistor dividers on the TSV524 op-amp channels, but I must admit that I'm not overly familiar with op-amps. Will users need a correction factor to apply to all analog readings?

Cheers,
Adam

![image](https://user-images.githubusercontent.com/22924092/100630752-f0e8d100-32f8-11eb-887a-5e456566d6ae.png)

**Comment by PaulZC** [comment]
Hi Adam (@adamgarbo ),
In this case, I suspect it is more to do with the op-amp not being able to swing all the way to the +ve rail.
With 3.3V on (e.g.) ADC0, you are asking pin 15 to swing to 3.3V and it probably can't do it...
There's no easy 'scale' fix for this. Once ADC0 drops below about 3.2V, pin 15 will faithfully follow the input 1:1.
The only ways to fix it would be to find a true rail-to-rail op-amp, or increase VCC for the op-amp by around 0.2V.
All the best,
Paul

**Comment by adamgarbo** [comment]
Thanks for the input @PaulZC! 

A tricky situation! Any thoughts @nseidle? The TSV524 op-amp also looks to be responsible for ~150 uA of quiescent draw that can't be disabled (to my knowledge), so it'd be great to address both issues in one fell swoop.

Cheers,
Adam

**Comment by nseidle** [comment]
The op-amp scaling is used to get the 2V max of the Apollo3 near the 3.3V ADC range of MicroMod. It's not perfect and as Paul points out is prone to clipping. 

And just to be the bearer of bad news, the op-amp is sitting behind the RTC diode which means it's max swing is about 2.9V. A good solution would be to move the TSV524 to be powered from the 'raw' side of the D7 diode. This should solve both your problems (TVS won't draw current when in sleep mode) and increase the overhead voltage a bit, but without a rail-to-rail opamp (as Paul points out) we'll be limited at the high end.

![image](https://user-images.githubusercontent.com/117102/101842559-9116d500-3b05-11eb-850f-06e08286a1b1.png)

**Comment by adamgarbo** [comment]
Thanks @nseidle & @PaulZC,

So to clarify for users, ADC measurements are currently not working on this version of Artemis Processor? 

Will this require a hardware revision to fix?

Cheers,
Adam

**Comment by PaulZC** [comment]
Hi @adamgarbo,

The ADC is working just fine. The only issue is that you do not quite have access to the full 3.3V range. Voltages up to 2.9V should be perfectly OK.

Best wishes,

Paul

**Comment by adamgarbo** [comment]
Thanks @PaulZC for the clarification. I could have better phrased the question as "not fully working as intended". 

Analog measurements have always been tricky with the Artemis. The argument could be made for end-users who rely on having a full range for ADC measurements that there's ultimately little difference between the Artemis' inherent 0-2 V range vs. the op-amp's 0-2.9 V range. It's usually an all or nothing situation.

I'm curious to see what the future holds for the Artemis Processor. While it'd be great to have scaling working across the entire range, it may be easier to simply remove the op-amp circuity and the onboard battery voltage divider, which users are currently unable to make use of.

Happy to assist in any way I can!

Cheers,
Adam

**Comment by adamgarbo** [comment]
Hi guys,

To confirm my earlier suspicions, I measured the deep sleep current draw of a brand new Artemis Processor this morning (R.I.P. the previous Artemis I accidentally blew up when first attempting this) and it was approximately 144.4 uA. 

With the current placement of the TSV524, is there any way to actually decrease the current draw, save for physically removing the op-amp?

Cheers,
Adam

**Comment by adamgarbo** [comment]
Issue closed as unresolved.
